In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values = (0, False, None, '', [], {})

In [3]:
any(falsy_values)

False

In [4]:
np.nan

nan

Todo lo que contenga nan "Not a Number" se queda en nan

In [5]:
3 + np.nan

nan

In [6]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [7]:
a.sum()

nan

In [8]:
a.mean()

nan

In [9]:
3 + None

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [10]:
a = np.array([1, 2, 3, np.nan, None, 4], dtype='float')

In [11]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [12]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [13]:
a.mean()

nan

Lo mismo sucede con inf

In [14]:
np.inf

inf

In [15]:
3 + np.inf

inf

In [16]:
np.inf / 3

inf

In [17]:
np.inf / np.inf

nan

In [19]:
b = np.array([1, 2, 3, np.inf, np.nan, 4], dtype=np.float64)

In [20]:
b.sum()

nan

Verificando nan o inf

In [21]:
np.isnan(np.nan)

True

In [22]:
np.isinf(np.inf)

True

In [23]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [24]:
np.isnan(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False,  True, False, False])

In [25]:
np.isinf(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([False, False, False, False,  True, False])

In [26]:
np.isfinite(np.array([1, 2, 3, np.nan, np.inf, 4]))

array([ True,  True,  True, False, False,  True])

In [27]:
a = np.array([1, 2, 3, np.nan, np.nan, 4])

In [28]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [29]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [30]:
a[np.isfinite(a)].sum()

10.0

In [31]:
a[np.isfinite(a)].mean()

2.5

para detectar null values

In [32]:
pd.isnull(np.nan)

True

In [33]:
pd.isnull(None)

True

In [34]:
pd.isna(np.nan)

True

In [35]:
pd.isna(None)

True

In [36]:
pd.notnull(None)

False

In [37]:
pd.notnull(np.nan)

False

In [38]:
pd.notna(np.nan)

False

In [39]:
pd.notnull(3)

True

In [40]:
pd.isnull(pd.Series([1, np.nan, 7]))

0    False
1     True
2    False
dtype: bool

In [41]:
pd.notnull(pd.Series([1, np.nan, 7]))

0     True
1    False
2     True
dtype: bool

In [42]:
pd.isnull(pd.DataFrame({
    'Column A': [1, np.nan, 7],
    'Column B': [np.nan, 2, 3],
    'Column C': [np.nan, 2, np.nan]
}))

   Column A  Column B  Column C
0     False      True      True
1      True     False     False
2     False     False      True

## Operaciones con valores fantantes

In [43]:
pd.Series([1, 2, np.nan]).count()

2

In [44]:
pd.Series([1, 2, np.nan]).sum()

3.0

In [45]:
pd.Series([2, 2, np.nan]).mean()

2.0

Filtrando informacion faltante

In [46]:
s = pd.Series([1, 2, 3, np.nan, np.nan, 4])

In [47]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [48]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [49]:
pd.notnull(s).sum()

4

In [50]:
pd.isnull(s).sum()

2

In [51]:
s[pd.notnull(s)]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [52]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [53]:
s.notnull()

0     True
1     True
2     True
3    False
4    False
5     True
dtype: bool

In [54]:
s[s.notnull()]

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

## Dropping null values

In [55]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [56]:
s.dropna()

0    1.0
1    2.0
2    3.0
5    4.0
dtype: float64

In [57]:
df = pd.DataFrame({
    'Column A': [1, np.nan, 30, np.nan],
    'Column B': [2, 8, 31, np.nan],
    'Column C': [np.nan, 9, 32, 100],
    'Column D': [5, 8, 34, 110],
})

In [58]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [59]:
df.shape

(4, 4)

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Column A  2 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  4 non-null      int64
dtypes: float64(3), int64(1)
memory usage: 260.0 bytes

In [61]:
df.isnull()

   Column A  Column B  Column C  Column D
0     False     False      True     False
1      True     False     False     False
2     False     False     False     False
3      True      True     False     False

In [62]:
df.isnull().sum()

Column A    2
Column B    1
Column C    1
Column D    0
dtype: int64

In [63]:
df.dropna()

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [64]:
df.dropna(axis=1)

   Column D
0         5
1         8
2        34
3       110

In [65]:
df2 = pd.DataFrame({
    'Column A': [1, np.nan, 30],
    'Column B': [2, np.nan, 31],
    'Column C': [np.nan, np.nan, 100]
})

In [66]:
df.dropna(how='all') #Elimina las filas que tengan todos los valores NAN

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [67]:
df.dropna(how='any') #Elimina las filas que tenga al menos 1 valor NAN

   Column A  Column B  Column C  Column D
2      30.0      31.0      32.0        34

In [68]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [69]:
df.dropna(thresh=3)

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34

In [70]:
df.dropna(thresh=3, axis='columns')

   Column B  Column C  Column D
0       2.0       NaN         5
1       8.0       9.0         8
2      31.0      32.0        34
3       NaN     100.0       110

## Filling null values

In [71]:
s

0    1.0
1    2.0
2    3.0
3    NaN
4    NaN
5    4.0
dtype: float64

In [72]:
s.fillna(0)

0    1.0
1    2.0
2    3.0
3    0.0
4    0.0
5    4.0
dtype: float64

In [73]:
s.fillna(s.mean())

0    1.0
1    2.0
2    3.0
3    2.5
4    2.5
5    4.0
dtype: float64

In [74]:
s.fillna(method='ffill')  #Completa con el ultimo valor leido, en este caso el 3

0    1.0
1    2.0
2    3.0
3    3.0
4    3.0
5    4.0
dtype: float64

In [75]:
s.fillna(method='bfill') #Completa con el valor siguiente, en este caso el 4

0    1.0
1    2.0
2    3.0
3    4.0
4    4.0
5    4.0
dtype: float64

In [76]:
pd.Series([np.nan, 3, np.nan, 9]).fillna(method='ffill') #El primer dato no cambia ya que no hay un valor antes del 0

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [77]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).fillna(method='bfill') # Los ultimos valores no cambian ya que no hay valores despues

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [78]:
df

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       NaN       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [79]:
df.fillna({'Column A': 0, 'Column B': 99, 'Column C': df['Column C'].mean()})

   Column A  Column B  Column C  Column D
0       1.0       2.0      47.0         5
1       0.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       0.0      99.0     100.0       110

In [80]:
df.fillna(method='ffill', axis=0) #Axis 0 es vertical filling

   Column A  Column B  Column C  Column D
0       1.0       2.0       NaN         5
1       1.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3      30.0      31.0     100.0       110

In [87]:
df.fillna(method='bfill', axis=0) #Axis 0 es vertical filling

   Column A  Column B  Column C  Column D
0       1.0       2.0       9.0         5
1      30.0       8.0       9.0         8
2      30.0      31.0      32.0        34
3       NaN       NaN     100.0       110

In [81]:
df.fillna(method='ffill', axis=1) #Axis 1 es Horizontal filling

   Column A  Column B  Column C  Column D
0       1.0       2.0       2.0       5.0
1       NaN       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3       NaN       NaN     100.0     110.0

In [88]:
df.fillna(method='bfill', axis=1) #Axis 1 es Horizontal filling

   Column A  Column B  Column C  Column D
0       1.0       2.0       5.0       5.0
1       8.0       8.0       9.0       8.0
2      30.0      31.0      32.0      34.0
3     100.0     100.0     100.0     110.0

## Revisar si hay NAs

In [82]:
s.dropna().count()

4

In [83]:
missing_values = len(s.dropna()) != len(s)
missing_values

True

In [84]:
len(s) #Nos muestra el tamaño de la serie

6

In [85]:
s.count() #Nos da la cantidad de elementos not null

4

In [86]:
missing_values = s.count() != len(s)
missing_values

True

In [89]:
pd.Series([True, False, False]).any()

True

In [90]:
pd.Series([True, False, False]).all()

False

In [91]:
pd.Series([True, True, True]).all()

True

In [92]:
s.isnull()

0    False
1    False
2    False
3     True
4     True
5    False
dtype: bool

In [93]:
pd.Series([1, np.nan]).isnull().any()

True

In [94]:
pd.Series([1, 2]).isnull().any()

False

In [95]:
s.isnull().any()

True

In [96]:
s.isnull().values

array([False, False, False,  True,  True, False])

In [97]:
s.isnull().values.any()

True

## Cleaning not null values

In [98]:
df = pd.DataFrame({
    'Sex': ['M', 'F', 'F', 'D', '?'],
    'Age': [29, 30, 24, 290, 25],
})
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D  290
4   ?   25

Los valores de 290 años y sexo D y ? representa valores invalidos

In [100]:
df['Sex'].unique()

array(['M', 'F', 'D', '?'], dtype=object)

In [101]:
df['Sex'].value_counts()

Sex
F    2
M    1
D    1
?    1
Name: count, dtype: int64

In [102]:
df['Sex'].replace('D', 'F') #Reemplaza la F por la D

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [103]:
df['Sex'].replace({'D': 'F', 'N': 'M'}) #Reemplaza la F por la D y la N por la M

0    M
1    F
2    F
3    F
4    ?
Name: Sex, dtype: object

In [104]:
df.replace({
    'Sex': {
        'D': 'F',
        'N': 'M'
    },
    'Age': {
        290: 29
    }
})

  Sex  Age
0   M   29
1   F   30
2   F   24
3   F   29
4   ?   25

In [105]:
df[df['Age'] > 100]

  Sex  Age
3   D  290

In [106]:
df.loc[df['Age'] > 100, 'Age'] = df.loc[df['Age'] > 100, 'Age'] / 10 
#podemos dividir por 10 ya que pudo ser un error de digitacion y la verdadera edad fuese 29

In [107]:
df

  Sex  Age
0   M   29
1   F   30
2   F   24
3   D   29
4   ?   25

## Valores Duplicados

In [108]:
ambassadors = pd.Series([
    'France',
    'United Kingdom',
    'United Kingdom',
    'Italy',
    'Germany',
    'Germany',
    'Germany',
], index=[
    'Gérard Araud',
    'Kim Darroch',
    'Peter Westmacott',
    'Armando Varricchio',
    'Peter Wittig',
    'Peter Ammon',
    'Klaus Scharioth '
])

In [109]:
ambassadors #Queremos dejar un embajador por pais

Gérard Araud                  France
Kim Darroch           United Kingdom
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
Peter Ammon                  Germany
Klaus Scharioth              Germany
dtype: object

In [110]:
ambassadors.duplicated() #Muestra los valores duplicados despues de leer el primero

Gérard Araud          False
Kim Darroch           False
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig          False
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [111]:
ambassadors.duplicated(keep='last') #Muestra los valores duplicados despues de leer el ultimo

Gérard Araud          False
Kim Darroch            True
Peter Westmacott      False
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth       False
dtype: bool

In [112]:
ambassadors.duplicated(keep=False) #Muestra todos los valores que tengan duplicados

Gérard Araud          False
Kim Darroch            True
Peter Westmacott       True
Armando Varricchio    False
Peter Wittig           True
Peter Ammon            True
Klaus Scharioth        True
dtype: bool

In [113]:
ambassadors.drop_duplicates() #Elimina los valores duplicados despues del primero

Gérard Araud                  France
Kim Darroch           United Kingdom
Armando Varricchio             Italy
Peter Wittig                 Germany
dtype: object

In [114]:
ambassadors.drop_duplicates(keep='last') #Mantiene el ultimo valor que no este duplicado y elimina los demas

Gérard Araud                  France
Peter Westmacott      United Kingdom
Armando Varricchio             Italy
Klaus Scharioth              Germany
dtype: object

In [115]:
ambassadors.drop_duplicates(keep=False) #Elimina todos los valores que tengan algun valor duplicado

Gérard Araud          France
Armando Varricchio     Italy
dtype: object

In [116]:
players = pd.DataFrame({
    'Name': [
        'Kobe Bryant',
        'LeBron James',
        'Kobe Bryant',
        'Carmelo Anthony',
        'Kobe Bryant',
    ],
    'Pos': [
        'SG',
        'SF',
        'SG',
        'SF',
        'SF'
    ]
})

In [117]:
players

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
2      Kobe Bryant  SG
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [118]:
players.duplicated()

0    False
1    False
2     True
3    False
4    False
dtype: bool

In [119]:
players.duplicated(subset=['Name'])

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [120]:
players.duplicated(subset=['Name'], keep='last') #Devuelve los valores duplicados segun la columna nombre

0     True
1    False
2     True
3    False
4    False
dtype: bool

In [121]:
players.drop_duplicates()

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

In [122]:
players.drop_duplicates(subset=['Name'])

              Name Pos
0      Kobe Bryant  SG
1     LeBron James  SF
3  Carmelo Anthony  SF

In [123]:
players.drop_duplicates(subset=['Name'], keep='last')

              Name Pos
1     LeBron James  SF
3  Carmelo Anthony  SF
4      Kobe Bryant  SF

## Dividir columnas

In [124]:
df = pd.DataFrame({
    'Data': [
        '1987_M_US _1',
        '1990?_M_UK_1',
        '1992_F_US_2',
        '1970?_M_   IT_1',
        '1985_F_I  T_2'
]})

In [125]:
df

              Data
0     1987_M_US _1
1     1990?_M_UK_1
2      1992_F_US_2
3  1970?_M_   IT_1
4    1985_F_I  T_2

In [136]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Year         5 non-null      object
 1   Sex          5 non-null      object
 2   Country      5 non-null      object
 3   No Children  5 non-null      object
dtypes: object(4)
memory usage: 292.0+ bytes

In [126]:
df['Data'].str.split('_') #Separa los valores que tengan _

0       [1987, M, US , 1]
1       [1990?, M, UK, 1]
2        [1992, F, US, 2]
3    [1970?, M,    IT, 1]
4      [1985, F, I  T, 2]
Name: Data, dtype: object

In [127]:
df['Data'].str.split('_', expand=True) #expand crea un dataframe

       0  1      2  3
0   1987  M    US   1
1  1990?  M     UK  1
2   1992  F     US  2
3  1970?  M     IT  1
4   1985  F   I  T  2

In [128]:
df = df['Data'].str.split('_', expand=True)

In [129]:
df.columns = ['Year', 'Sex', 'Country', 'No Children']

In [130]:
df

    Year Sex Country No Children
0   1987   M     US            1
1  1990?   M      UK           1
2   1992   F      US           2
3  1970?   M      IT           1
4   1985   F    I  T           2

In [131]:
df['Year'].str.contains('\?')

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool

In [132]:
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

In [133]:
df['Country'].str.strip()

0      US
1      UK
2      US
3      IT
4    I  T
Name: Country, dtype: object

In [134]:
df['Country'].str.replace(' ', '')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

In [135]:
df['Year'].str.replace(r'(?P<year>\d{4})\?', lambda m: m.group('year'))

ValueError: Cannot use a callable replacement when regex=False