In [1]:
import pandas as pd

## Reading with python

In [2]:
filepath = 'C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv'

with open(filepath, 'r') as reader:
    print(reader)

<_io.TextIOWrapper name='C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv' mode='r' encoding='cp1252'>

In [3]:
filepath = 'C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv'

with open(filepath, 'r') as reader:
    for index, line in enumerate(reader.readlines()):
        # read just the first 10 lines
        if (index < 10):
            print(index, line)

0 2017-04-02 00:00:00,1099.169125

1 2017-04-03 00:00:00,1141.813

2 2017-04-04 00:00:00,1141.6003625

3 2017-04-05 00:00:00,1133.0793142857142

4 2017-04-06 00:00:00,1196.3079375

5 2017-04-07 00:00:00,1190.45425

6 2017-04-08 00:00:00,1181.1498375

7 2017-04-09 00:00:00,1208.8005

8 2017-04-10 00:00:00,1207.744875

9 2017-04-11 00:00:00,1226.6170375

## Reading with Pandas
The first method we'll learn is read_csv, that let us read comma-separated values (CSV) files and raw text (TXT) files into a DataFrame.

The read_csv function is extremely powerful and you can specify a very broad set of parameters at import time that allow us to accurately configure how the data will be read and parsed by specifying the correct structure, enconding and other details. The most common parameters are as follows:

    filepath: Path of the file to be read.
    sep: Character(s) that are used as a field separator in the file.
    header: Index of the row containing the names of the columns (None if none).
    index_col: Index of the column or sequence of indexes that should be used as index of rows of the data.
    names: Sequence containing the names of the columns (used together with header = None).
    skiprows: Number of rows or sequence of row indexes to ignore in the load.
    na_values: Sequence of values that, if found in the file, should be treated as NaN.
    dtype: Dictionary in which the keys will be column names and the values will be types of NumPy to which their content must be converted.
    parse_dates: Flag that indicates if Python should try to parse data with a format similar to dates as dates. You can enter a list of column names that must be joined for the parsing as a date.
    date_parser: Function to use to try to parse dates.
    nrows: Number of rows to read from the beginning of the file.
    skip_footer: Number of rows to ignore at the end of the file.
    encoding: Encoding to be expected from the file read.
    squeeze: Flag that indicates that if the data read only contains one column the result is a Series instead of a DataFrame.
    thousands: Character to use to detect the thousands separator.
    decimal: Character to use to detect the decimal separator.
    skip_blank_lines: Flag that indicates whether blank lines should be ignored.
    
Any valid string path is acceptable. The string could be a URL. Valid URL schemes include HTTP, FTP, S3, and file. For file URLs, a host is expected.

In [37]:
pd.read_csv?

In [4]:
df = pd.read_csv('C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv')

df.head()

   2017-04-02 00:00:00  1099.169125
0  2017-04-03 00:00:00  1141.813000
1  2017-04-04 00:00:00  1141.600363
2  2017-04-05 00:00:00  1133.079314
3  2017-04-06 00:00:00  1196.307937
4  2017-04-07 00:00:00  1190.454250

El dataframe tiene 2 columnas, la primera timestamp y la segunda Price, en este caso esta tomando como header el primer dato de cada columna, lo cual no es correcto

In [5]:

df = pd.read_csv('C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv',
                 header=None)

In [6]:
df.head()

                     0            1
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

Podemos identificar los valores NAN que contenga el dataframe, los cuales los podemos reconocer con los caracteres '-' , ' ' , '?'

In [7]:
df = pd.read_csv('C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'])

In [8]:
df.head()

                     0            1
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

## Asignar nombre a las columnas

In [9]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'])

In [10]:
df.head()

             Timestamp        Price
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

## Tipo de columnas usando Dtype

In [11]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'})

In [12]:
df.head()

             Timestamp        Price
0  2017-04-02 00:00:00  1099.169125
1  2017-04-03 00:00:00  1141.813000
2  2017-04-04 00:00:00  1141.600363
3  2017-04-05 00:00:00  1133.079314
4  2017-04-06 00:00:00  1196.307937

In [13]:
df.dtypes

Timestamp     object
Price        float64
dtype: object

In [14]:
pd.to_datetime(df['Timestamp']).head()

0   2017-04-02
1   2017-04-03
2   2017-04-04
3   2017-04-05
4   2017-04-06
Name: Timestamp, dtype: datetime64[ns]

In [15]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [16]:
df.head()

   Timestamp        Price
0 2017-04-02  1099.169125
1 2017-04-03  1141.813000
2 2017-04-04  1141.600363
3 2017-04-05  1133.079314
4 2017-04-06  1196.307937

In [17]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

Tambien se puede cambiar a datetime usando parse_dates

In [18]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0])

In [19]:
df.head()

   Timestamp        Price
0 2017-04-02  1099.169125
1 2017-04-03  1141.813000
2 2017-04-04  1141.600363
3 2017-04-05  1133.079314
4 2017-04-06  1196.307937

In [20]:
df.dtypes

Timestamp    datetime64[ns]
Price               float64
dtype: object

## Agregando Index

In [21]:
df = pd.read_csv('btc-market-price.csv',
                 header=None,
                 na_values=['', '?', '-'],
                 names=['Timestamp', 'Price'],
                 dtype={'Price': 'float'},
                 parse_dates=[0],
                 index_col=[0])

In [22]:
df.head()

                  Price
Timestamp
2017-04-02  1099.169125
2017-04-03  1141.813000
2017-04-04  1141.600363
2017-04-05  1133.079314
2017-04-06  1196.307937

## Ejemplo 2

In [23]:
exam_df = pd.read_csv('C:/Users/braya/OneDrive - Universidad Nacional Abierta y a Distancia/Desktop/DATA ANALYSIS/exam_review.csv')

In [24]:
exam_df

                               first_name>last_name>age>math_score>french_score
Ray>Morley>18>"68     000">"75                                             000"
Melvin>Scott>24>77>83 NaN                                                   NaN
Amirah>Haley>22>92>67 NaN                                                   NaN
Gerard>Mills>19>"78   000">72                                               NaN
Amy>Grimes>23>91>81   NaN                                                   NaN

Vamos a separar los datos en columnas de acuerdo a simbolo >

In [25]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>')

In [26]:
exam_df

  first_name last_name  age math_score french_score
0        Ray    Morley   18     68,000       75,000
1     Melvin     Scott   24         77           83
2     Amirah     Haley   22         92           67
3     Gerard     Mills   19     78,000           72
4        Amy    Grimes   23         91           81

In [27]:
exam_df[['math_score', 'french_score']].dtypes

math_score      object
french_score    object
dtype: object

Vamos a cambiar el dtype a decimal

In [28]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',')

In [29]:
exam_df

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18        68.0          75.0
1     Melvin     Scott   24        77.0          83.0
2     Amirah     Haley   22        92.0          67.0
3     Gerard     Mills   19        78.0          72.0
4        Amy    Grimes   23        91.0          81.0

In [30]:
exam_df[['math_score', 'french_score']].dtypes

math_score      float64
french_score    float64
dtype: object

In [31]:
pd.read_csv('exam_review.csv',
            sep='>',
            thousands=',')

  first_name last_name  age  math_score  french_score
0        Ray    Morley   18       68000         75000
1     Melvin     Scott   24          77            83
2     Amirah     Haley   22          92            67
3     Gerard     Mills   19       78000            72
4        Amy    Grimes   23          91            81

In [32]:
exam_df[['math_score', 'french_score']].dtypes

math_score      float64
french_score    float64
dtype: object

Si queremos leer primero las 2 primeras filas del data frame lo hacemos de la siguiente forma:

In [33]:
pd.read_csv('exam_review.csv',
            sep='>',
            skiprows=2)

   Melvin   Scott  24      77  83
0  Amirah   Haley  22      92  67
1  Gerard   Mills  19  78,000  72
2     Amy  Grimes  23      91  81

In [34]:
exam_df = pd.read_csv('exam_review.csv',
                      sep='>',
                      decimal=',',
                      skiprows=[1,3])
#el header se considera row 1, si queremos skipear las filas 1 y 3, entonces:

In [35]:
exam_df

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81

## Get rid of blank lines

The skip_blank_lines parameter is set to True so blank lines are skipped while we read files.

If we set this parameter to False, then every blank line will be loaded with NaN values into the DataFrame.

In [36]:
pd.read_csv('exam_review.csv',
            sep='>',
            skip_blank_lines=False)

  first_name last_name   age math_score french_score
0        Ray    Morley  18.0     68,000       75,000
1     Melvin     Scott  24.0         77           83
2     Amirah     Haley  22.0         92           67
3        NaN       NaN   NaN        NaN          NaN
4     Gerard     Mills  19.0     78,000           72
5        Amy    Grimes  23.0         91           81

## Cargar columnas especificas

In [38]:
pd.read_csv('exam_review.csv',
            usecols=['first_name', 'last_name', 'age'],
            sep='>')

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

In [39]:
pd.read_csv('exam_review.csv',
            usecols=[0, 1, 2],
            sep='>')

  first_name last_name  age
0        Ray    Morley   18
1     Melvin     Scott   24
2     Amirah     Haley   22
3     Gerard     Mills   19
4        Amy    Grimes   23

## Series
Podemos usar series en vez de dataframes

In [40]:
exam_test_1 = pd.read_csv('exam_review.csv',
                          sep='>',
                          usecols=['last_name'])

In [41]:
type(exam_test_1)

pandas.core.frame.DataFrame

## Save to CSV

In [43]:
exam_df.to_csv()

',first_name,last_name,age,math_score,french_score\r\n0,Melvin,Scott,24,77.0,83\r\n1,Gerard,Mills,19,78.0,72\r\n2,Amy,Grimes,23,91.0,81\r\n'

In [44]:
exam_df.to_csv('out.csv') #Out es el nombre del archivo que se va a guardar

In [45]:
pd.read_csv('out.csv')

   Unnamed: 0 first_name last_name  age  math_score  french_score
0           0     Melvin     Scott   24        77.0            83
1           1     Gerard     Mills   19        78.0            72
2           2        Amy    Grimes   23        91.0            81

In [46]:
exam_df.to_csv('out.csv',
               index=None)

In [47]:

pd.read_csv('out.csv')

  first_name last_name  age  math_score  french_score
0     Melvin     Scott   24        77.0            83
1     Gerard     Mills   19        78.0            72
2        Amy    Grimes   23        91.0            81